server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 2233d
    url: jdbc:mysql://10.82.13.208:3306/springboot_test
  jpa:
    hibernate:
      ddl-auto: update #自动根据实体类创建和跟新数据库
    show-sql: true #实现sql打印
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #设置搜索引擎
