server:
  port: 8089
spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 2233d
    url: jdbc:mysql://10.82.13.208:3306/springboot_test?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update #自动根据实体类创建和跟新数据库
    show-sql: true #实现sql打印
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #设置搜索引擎
